---
title: "svm_tigers_prediction"
author: "Xavier Owens"
date: "4/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(fastDummies)
library(dplyr)

#SVM
dat <- read_csv("2010_2019_DET_w_weather.csv")
dat <- select(dat, c("DH_Game","Year", "DOW", "Away", "H_Game_number","A_Game_number", "H_Wins","A_Wins","Game_Time","Attendance", "PRCP", "TMAX", "TMIN",WT01,WT03,WT07, WT08, WT16,WT18))

#dat <-dat[-1]
dat$DOW <- as.factor(dat$DOW)
dat$DH_Game <- as.factor(dat$DH_Game)
dat$Year <- as.factor(dat$Year)
dat$Away <- as.factor(dat$Away)
dat$Game_Time <- as.factor(dat$Game_Time)

dat <- dummy_cols(dat, select_columns = c("DOW","DH_Game","Year", "Away", "Game_Time"))
dat$DOW <- NULL
dat$DH_Game <- NULL
dat$Year <- NULL
dat$Away <- NULL
dat$Game_Time <- NULL

dat$home_win_perc <- round((dat$H_Wins/dat$H_Game_number),2)
dat$away_win_perc <- round((dat$H_Wins/dat$H_Game_number),2)


normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}
#dat[2:4] <- as.data.frame(lapply(dat[2:4], normalize))

## 75% of the sample size
smp_size <- floor(0.75 * nrow(dat))

## set the seed to make your partition reproducible
set.seed(123)
train_ind <- sample(seq_len(nrow(dat)), size = smp_size)

train <-dat[train_ind, ]
test <- dat[-train_ind, ]

```


```{r}
#with bagging
library(randomForest)
#Random Forest
rf <- randomForest(Attendance ~.,data = train, mtry=22, importance = TRUE, ntree = 1000)
rf
varImpPlot(rf, n.var =10)

model.rf.predictions <- predict(rf, test)
model.rf.predictions <- as.integer(round(model.rf.predictions))

oosmae_rf <- abs((test$Attendance-model.rf.predictions))
summary(oosmae_rf)

oosmse_rf <- mean((test$Attendance-model.rf.predictions)^2)
summary(oosmse_rf)

rf_pred_error <- test$Attendance-model.rf.predictions
rf_within_3000 <- round(length(rf_pred_error[rf_pred_error >= -3000 & rf_pred_error <=3000])/length(rf_pred_error),2)
rf_within_3000*100
plot(x=test$Attendance, y=model.rf.predictions, 
       xlab="Actual Attendance", ylab="Predicted Attendance")
  abline(a=0,b=1) 

```

About `r rf_within_3000*100`% of attendance predictions were within 3000 attendees of the actual attendance.

```{r}
#SVM Model
library(kernlab)
model.1 <- ksvm(Attendance ~ ., data = train,
                          kernel = "polydot", type = "eps-bsvr")

# look at basic information about the model
model.1

## Step 3: Evaluating model performance 
# predictions on testing dataset
model.1.predictions <- predict(model.1, test)
model.1.predictions <- as.integer(round(model.1.predictions))

oosmae_svm <- abs((test$Attendance-model.1.predictions))
summary(oosmae_svm)

oosmse_svm <- mean((test$Attendance-model.1.predictions)^2)
summary(oosmse_svm)

svm_pred_error <- test$Attendance-model.1.predictions
svm_within_3000 <- round(length(svm_pred_error[svm_pred_error >= -3000 & svm_pred_error <=3000])/length(svm_pred_error),2)
svm_within_3000*100


plot(x=test$Attendance, y=model.1.predictions, 
       xlab="Actual Attendance", ylab="Predicted Attendance")
  abline(a=0,b=1) 

lmsvm_model <- lm(test$Attendance~model.1.predictions)
summary(lmsvm_model)

```
About `r svm_within_3000*100`% of attendance predictions were within 3000 attendees of the actual attendance.
